# -*- coding: utf-8 -*-
"""AluraStoreLatam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118HRjcMdOOMmJP-_3wHMZZCsDuoZXoWh

### Importación de datos
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""principalemte tenemos los linsk de la base de datos de las 4 tiendas con las cuales vamos a trabajar con la finalidad de ver cual de las tiendas le podemos dar de baja

#1. Análisis de facturación
"""

tienda["Total_Venta"] = tienda["Precio"] + tienda["Costo de envío"]
tienda2["Total_Venta"] = tienda2["Precio"] + tienda2["Costo de envío"]
tienda3["Total_Venta"] = tienda3["Precio"] + tienda3["Costo de envío"]
tienda4["Total_Venta"] = tienda4["Precio"] + tienda4["Costo de envío"]


facturacion_t1 = tienda["Total_Venta"].sum()
facturacion_t2 = tienda2["Total_Venta"].sum()
facturacion_t3 = tienda3["Total_Venta"].sum()
facturacion_t4 = tienda4["Total_Venta"].sum()

print("💰 Facturación por tienda:")
print(f"Tienda 1: ${facturacion_t1:,.2f}")
print(f"Tienda 2: ${facturacion_t2:,.2f}")
print(f"Tienda 3: ${facturacion_t3:,.2f}")
print(f"Tienda 4: ${facturacion_t4:,.2f}")

"""para el analizis de la facturacion tomamos en cuenta los montos establecidos entre precio + costo de envio dando como resultante el precio total de la venta en donde la tienda 4 es la que menos cotizacion monetaria tiene

# 2. Ventas por categoría
"""

# Corregir nombre de la primera columna
tienda.rename(columns={"Categoría del Producto ": "Categoría del Producto"}, inplace=True)

# Obtener el tipo de producto de cada tienda
categoria_t1 = tienda["Categoría del Producto"].iloc[0]
categoria_t2 = tienda2["Categoría del Producto"].iloc[0]
categoria_t3 = tienda3["Categoría del Producto"].iloc[0]
categoria_t4 = tienda4["Categoría del Producto"].iloc[0]

# Mostrar resultados
print("🏬 Tipo de producto por tienda:")
print(f"Tienda 1 → {categoria_t1}")
print(f"Tienda 2 → {categoria_t2}")
print(f"Tienda 3 → {categoria_t3}")
print(f"Tienda 4 → {categoria_t4}")

"""En esta seccion tenemos las ventas por categoria en la cual describimos que tipo de prodcutos vende cada tienda, donde teniendo presente el estima de la tarea podemos descartar la tienda 4 por duplicidad de ventas

# 3. Calificación promedio de la tienda
"""

# Promedio de calificación por tienda
promedio_t1 = tienda["Calificación"].mean()
promedio_t2 = tienda2["Calificación"].mean()
promedio_t3 = tienda3["Calificación"].mean()
promedio_t4 = tienda4["Calificación"].mean()

print("⭐ Promedio de calificación por tienda:")
print(f"Tienda 1 → {promedio_t1:.2f}")
print(f"Tienda 2 → {promedio_t2:.2f}")
print(f"Tienda 3 → {promedio_t3:.2f}")
print(f"Tienda 4 → {promedio_t4:.2f}")

"""En terminos de promedio de cada tienda pordemos decartar con facilidad la tienda #1 ya que tiene un indice mas bajo

# 4. Productos más y menos vendidos
"""

producto_mas_vendido_t1 = tienda["Producto"].value_counts().idxmax()
producto_mas_vendido_t2 = tienda2["Producto"].value_counts().idxmax()
producto_mas_vendido_t3 = tienda3["Producto"].value_counts().idxmax()
producto_mas_vendido_t4 = tienda4["Producto"].value_counts().idxmax()

print("🏆 Producto más vendido por tienda:")
print(f"Tienda 1 → {producto_mas_vendido_t1}")
print(f"Tienda 2 → {producto_mas_vendido_t2}")
print(f"Tienda 3 → {producto_mas_vendido_t3}")
print(f"Tienda 4 → {producto_mas_vendido_t4}")

# Producto menos vendido (por cantidad de ventas)
producto_menos_vendido_t1 = tienda["Producto"].value_counts().idxmin()
producto_menos_vendido_t2 = tienda2["Producto"].value_counts().idxmin()
producto_menos_vendido_t3 = tienda3["Producto"].value_counts().idxmin()
producto_menos_vendido_t4 = tienda4["Producto"].value_counts().idxmin()

print("🧊 Producto menos vendido por tienda:")
print(f"Tienda 1 → {producto_menos_vendido_t1}")
print(f"Tienda 2 → {producto_menos_vendido_t2}")
print(f"Tienda 3 → {producto_menos_vendido_t3}")
print(f"Tienda 4 → {producto_menos_vendido_t4}")

"""En esta parte tenemos lo que hes la categorizacion y segmentacion de lso productos mas y menos vendidos en las tiendas

# 5. Envío promedio por tienda
"""

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)


# Promedio de envío por tienda
envio_prom_t1 = tienda["Costo de envío"].mean()
envio_prom_t2 = tienda2["Costo de envío"].mean()
envio_prom_t3 = tienda3["Costo de envío"].mean()
envio_prom_t4 = tienda4["Costo de envío"].mean()

print("🚚 Promedio de envío por tienda:")
print(f"Tienda 1 → ${envio_prom_t1:.2f}")
print(f"Tienda 2 → ${envio_prom_t2:.2f}")
print(f"Tienda 3 → ${envio_prom_t3:.2f}")
print(f"Tienda 4 → ${envio_prom_t4:.2f}")

"""En esta tenemos la cantidad proporcioanl de envios por tienda con un desempeño mas bajo la #4

# **Como resultado despies del analizis de los datos anteriores, podemos deducir que la tienda que deberia sacar de funcionamiento es la numero 4 ya que tiene falencia en 3 de 5 criterios a comparacion de las otras tiendas**
"""